name: Build Desktop Apps
on:
  push:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: macos-latest
            # Updated to look in all subfolders of bundle
            artifact_path: src-tauri/target/release/bundle/**/*.dmg
          - platform: windows-latest
            # Updated to look in all subfolders of bundle
            artifact_path: src-tauri/target/release/bundle/**/*.exe

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Dependencies
        run: npm install

      - name: Build Tauri App
        run: npm run tauri build

      - name: Upload Files
        uses: actions/upload-artifact@v4
        with:
          name: Match3-Architect-${{ matrix.platform }}
          # This uses the path defined in the matrix above
          path: ${{ matrix.artifact_path }}
          if-no-files-found: error